### ISSUE TITLE
enGB (British English) plus deDE (German Standard German)

### ISSUE THREAD

**Issue by ghost** [SebastianMuskalla/enUSplusdeDEBilingualDictionary#1]
Thanks for your dictionary, @SebastianMuskalla!
Would you mind also providing a enGB (British English) plus deDE (German Standard German) bilingual dictionary?

**Comment by SebastianMuskalla** [comment]
Thanks for the kind request.
Unfortunately, I am quite busy at the moment, so I can't promise that I will find the time to create a British English version  of the dictionary.

However, creating the dictionary was not too difficult. In particular, it doesn't require much technical knowledge.
If you want to try to create it yourself, you can take a look at the section "How has this been created?" of the README file and at the `steps/` directory in the repository.
